pipeline {

    agent any

    environment {
        REGISTRY = "80869538/frontend"
        registryCredential = 'dockerhub'
        dockerImage = ''
    }
    options {
        skipDefaultCheckout true
    }
    
    stages {
        stage('clean_workspace_and_checkout_source') {
            steps {
                cleanWs()
                checkout scm
            }
        }
        stage('Prepare Docker Environment'){
            steps {
                sh 'echo "y" | sudo docker system prune -a'
            }
        }


        stage('Build') { 
            steps {
                sh 'npm install' 
            }
            
        }

        stage('Test'){
            steps {
                sh 'npm run test'
            }
        }

        stage('Building App image'){
            steps{
                script {
                    dockerImage = docker.build REGISTRY + ":latest"   
                }
            }
        }

        stage('Push Image') {
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                    dockerImage.push()
                    }
                }
            }
        }   

        stage('Remove Unused docker image') {
            steps{
                sh 'echo "y" | sudo docker system prune -a'
            }
        }

        stage("Deploy"){
            steps{
                script{
                if(env.BRANCH_NAME == 'master'){
                        sh 'chmod 400 Team2122.pem'
                        sh 'ssh -i "Team2122.pem" -o "StrictHostKeyChecking no" ubuntu@ec2-52-68-78-115.ap-northeast-1.compute.amazonaws.com "bash -s" < ./jenkins/deploy.sh'
                }
                else{
                    echo "no deploy"
            }

            }
            
            }

        }
    }
}